---
- hosts: localhost
  connection: local
  vars_prompt:
  - name: commercial_type
    prompt: "Enter the wanted type for the instances"
    default: DEV1-S
    private: no
  - name: vmprefix
    prompt: "Enter a prefix for the VM names"
    default: "proxmox"
    private: no
  tasks:
  - name: Gather Scaleway images facts
    scaleway_image_facts:
      region: par1
  - name: Find a suitable Debian Stretch x86 image
    set_fact:
      x86image: "{{item.id}}"
    when: item.arch == "x86_64" and item.name == "Debian Stretch" and item.root_volume.size == 10000000000
    loop: "{{ scaleway_image_facts }}"
  - name: Gather Scaleway organizations facts
    scaleway_organization_facts:

  - name: "Add SSH key"
    scaleway_sshkey:
      ssh_pub_key: "{{lookup('file', 'admin.pub') }}"
      state: "present"

  - name: "Create my servers"
    scaleway_compute:
      name: "{{vmprefix}}{{item}}"
      state: running
      image: "{{x86image}}"
      organization: "{{scaleway_organization_facts[0].id}}"
      region: par1
      commercial_type: "{{commercial_type}}"
      wait: true
      tags: proxmoxve
      public_ip: dynamic
    loop: "{{ range(1, 3 + 1)|list }}"
